# For postgres database running in a docker container, you have to use the driverClassName. By
# using the dataSourceClassName, you cannot connect to the database from another docker container.
driverClassName: ${db.driverClassName:org.postgresql.Driver}
jdbcUrl: ${db.jdbcUrl:jdbc:postgresql://timescale:5432/configserver}
username: ${db.username:postgres}
password: ${db.password:secret}
maximumPoolSize: ${db.maximumPoolSize:3}
