/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.lightapi.portal.host;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class HostUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5939805138407965993L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HostUpdatedEvent\",\"namespace\":\"net.lightapi.portal.host\",\"fields\":[{\"name\":\"EventId\",\"type\":{\"type\":\"record\",\"name\":\"EventId\",\"namespace\":\"com.networknt.kafka.common\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"a unique identifier for the event\"},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the user who creates the event\"},{\"name\":\"hostId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the host which is the event is created\"},{\"name\":\"nonce\",\"type\":\"long\",\"doc\":\"the number of the transactions for the user\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"time the event is recorded\",\"default\":0},{\"name\":\"derived\",\"type\":\"boolean\",\"doc\":\"indicate if the event is derived from event processor\",\"default\":false}]}},{\"name\":\"hostId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host id\"},{\"name\":\"domain\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host domain\"},{\"name\":\"subDomain\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host subdomain\"},{\"name\":\"hostDesc\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host desc\"},{\"name\":\"hostOwner\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host owner\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HostUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HostUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HostUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HostUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HostUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HostUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HostUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HostUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HostUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.networknt.kafka.common.EventId EventId;
  /** host id */
  private java.lang.String hostId;
  /** host domain */
  private java.lang.String domain;
  /** host subdomain */
  private java.lang.String subDomain;
  /** host desc */
  private java.lang.String hostDesc;
  /** host owner */
  private java.lang.String hostOwner;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HostUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param EventId The new value for EventId
   * @param hostId host id
   * @param domain host domain
   * @param subDomain host subdomain
   * @param hostDesc host desc
   * @param hostOwner host owner
   */
  public HostUpdatedEvent(com.networknt.kafka.common.EventId EventId, java.lang.String hostId, java.lang.String domain, java.lang.String subDomain, java.lang.String hostDesc, java.lang.String hostOwner) {
    this.EventId = EventId;
    this.hostId = hostId;
    this.domain = domain;
    this.subDomain = subDomain;
    this.hostDesc = hostDesc;
    this.hostOwner = hostOwner;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return EventId;
    case 1: return hostId;
    case 2: return domain;
    case 3: return subDomain;
    case 4: return hostDesc;
    case 5: return hostOwner;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: EventId = (com.networknt.kafka.common.EventId)value$; break;
    case 1: hostId = value$ != null ? value$.toString() : null; break;
    case 2: domain = value$ != null ? value$.toString() : null; break;
    case 3: subDomain = value$ != null ? value$.toString() : null; break;
    case 4: hostDesc = value$ != null ? value$.toString() : null; break;
    case 5: hostOwner = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'EventId' field.
   * @return The value of the 'EventId' field.
   */
  public com.networknt.kafka.common.EventId getEventId() {
    return EventId;
  }


  /**
   * Sets the value of the 'EventId' field.
   * @param value the value to set.
   */
  public void setEventId(com.networknt.kafka.common.EventId value) {
    this.EventId = value;
  }

  /**
   * Gets the value of the 'hostId' field.
   * @return host id
   */
  public java.lang.String getHostId() {
    return hostId;
  }


  /**
   * Sets the value of the 'hostId' field.
   * host id
   * @param value the value to set.
   */
  public void setHostId(java.lang.String value) {
    this.hostId = value;
  }

  /**
   * Gets the value of the 'domain' field.
   * @return host domain
   */
  public java.lang.String getDomain() {
    return domain;
  }


  /**
   * Sets the value of the 'domain' field.
   * host domain
   * @param value the value to set.
   */
  public void setDomain(java.lang.String value) {
    this.domain = value;
  }

  /**
   * Gets the value of the 'subDomain' field.
   * @return host subdomain
   */
  public java.lang.String getSubDomain() {
    return subDomain;
  }


  /**
   * Sets the value of the 'subDomain' field.
   * host subdomain
   * @param value the value to set.
   */
  public void setSubDomain(java.lang.String value) {
    this.subDomain = value;
  }

  /**
   * Gets the value of the 'hostDesc' field.
   * @return host desc
   */
  public java.lang.String getHostDesc() {
    return hostDesc;
  }


  /**
   * Sets the value of the 'hostDesc' field.
   * host desc
   * @param value the value to set.
   */
  public void setHostDesc(java.lang.String value) {
    this.hostDesc = value;
  }

  /**
   * Gets the value of the 'hostOwner' field.
   * @return host owner
   */
  public java.lang.String getHostOwner() {
    return hostOwner;
  }


  /**
   * Sets the value of the 'hostOwner' field.
   * host owner
   * @param value the value to set.
   */
  public void setHostOwner(java.lang.String value) {
    this.hostOwner = value;
  }

  /**
   * Creates a new HostUpdatedEvent RecordBuilder.
   * @return A new HostUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.host.HostUpdatedEvent.Builder newBuilder() {
    return new net.lightapi.portal.host.HostUpdatedEvent.Builder();
  }

  /**
   * Creates a new HostUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HostUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.host.HostUpdatedEvent.Builder newBuilder(net.lightapi.portal.host.HostUpdatedEvent.Builder other) {
    if (other == null) {
      return new net.lightapi.portal.host.HostUpdatedEvent.Builder();
    } else {
      return new net.lightapi.portal.host.HostUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new HostUpdatedEvent RecordBuilder by copying an existing HostUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new HostUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.host.HostUpdatedEvent.Builder newBuilder(net.lightapi.portal.host.HostUpdatedEvent other) {
    if (other == null) {
      return new net.lightapi.portal.host.HostUpdatedEvent.Builder();
    } else {
      return new net.lightapi.portal.host.HostUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for HostUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HostUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<HostUpdatedEvent> {

    private com.networknt.kafka.common.EventId EventId;
    private com.networknt.kafka.common.EventId.Builder EventIdBuilder;
    /** host id */
    private java.lang.String hostId;
    /** host domain */
    private java.lang.String domain;
    /** host subdomain */
    private java.lang.String subDomain;
    /** host desc */
    private java.lang.String hostDesc;
    /** host owner */
    private java.lang.String hostOwner;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.lightapi.portal.host.HostUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasEventIdBuilder()) {
        this.EventIdBuilder = com.networknt.kafka.common.EventId.newBuilder(other.getEventIdBuilder());
      }
      if (isValidValue(fields()[1], other.hostId)) {
        this.hostId = data().deepCopy(fields()[1].schema(), other.hostId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.domain)) {
        this.domain = data().deepCopy(fields()[2].schema(), other.domain);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.subDomain)) {
        this.subDomain = data().deepCopy(fields()[3].schema(), other.subDomain);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.hostDesc)) {
        this.hostDesc = data().deepCopy(fields()[4].schema(), other.hostDesc);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.hostOwner)) {
        this.hostOwner = data().deepCopy(fields()[5].schema(), other.hostOwner);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing HostUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(net.lightapi.portal.host.HostUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = true;
      }
      this.EventIdBuilder = null;
      if (isValidValue(fields()[1], other.hostId)) {
        this.hostId = data().deepCopy(fields()[1].schema(), other.hostId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.domain)) {
        this.domain = data().deepCopy(fields()[2].schema(), other.domain);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.subDomain)) {
        this.subDomain = data().deepCopy(fields()[3].schema(), other.subDomain);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.hostDesc)) {
        this.hostDesc = data().deepCopy(fields()[4].schema(), other.hostDesc);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.hostOwner)) {
        this.hostOwner = data().deepCopy(fields()[5].schema(), other.hostOwner);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'EventId' field.
      * @return The value.
      */
    public com.networknt.kafka.common.EventId getEventId() {
      return EventId;
    }


    /**
      * Sets the value of the 'EventId' field.
      * @param value The value of 'EventId'.
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder setEventId(com.networknt.kafka.common.EventId value) {
      validate(fields()[0], value);
      this.EventIdBuilder = null;
      this.EventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'EventId' field has been set.
      * @return True if the 'EventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'EventId' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.networknt.kafka.common.EventId.Builder getEventIdBuilder() {
      if (EventIdBuilder == null) {
        if (hasEventId()) {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder(EventId));
        } else {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder());
        }
      }
      return EventIdBuilder;
    }

    /**
     * Sets the Builder instance for the 'EventId' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public net.lightapi.portal.host.HostUpdatedEvent.Builder setEventIdBuilder(com.networknt.kafka.common.EventId.Builder value) {
      clearEventId();
      EventIdBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'EventId' field has an active Builder instance
     * @return True if the 'EventId' field has an active Builder instance
     */
    public boolean hasEventIdBuilder() {
      return EventIdBuilder != null;
    }

    /**
      * Clears the value of the 'EventId' field.
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder clearEventId() {
      EventId = null;
      EventIdBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'hostId' field.
      * host id
      * @return The value.
      */
    public java.lang.String getHostId() {
      return hostId;
    }


    /**
      * Sets the value of the 'hostId' field.
      * host id
      * @param value The value of 'hostId'.
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder setHostId(java.lang.String value) {
      validate(fields()[1], value);
      this.hostId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'hostId' field has been set.
      * host id
      * @return True if the 'hostId' field has been set, false otherwise.
      */
    public boolean hasHostId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'hostId' field.
      * host id
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder clearHostId() {
      hostId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'domain' field.
      * host domain
      * @return The value.
      */
    public java.lang.String getDomain() {
      return domain;
    }


    /**
      * Sets the value of the 'domain' field.
      * host domain
      * @param value The value of 'domain'.
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder setDomain(java.lang.String value) {
      validate(fields()[2], value);
      this.domain = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'domain' field has been set.
      * host domain
      * @return True if the 'domain' field has been set, false otherwise.
      */
    public boolean hasDomain() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'domain' field.
      * host domain
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder clearDomain() {
      domain = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'subDomain' field.
      * host subdomain
      * @return The value.
      */
    public java.lang.String getSubDomain() {
      return subDomain;
    }


    /**
      * Sets the value of the 'subDomain' field.
      * host subdomain
      * @param value The value of 'subDomain'.
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder setSubDomain(java.lang.String value) {
      validate(fields()[3], value);
      this.subDomain = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'subDomain' field has been set.
      * host subdomain
      * @return True if the 'subDomain' field has been set, false otherwise.
      */
    public boolean hasSubDomain() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'subDomain' field.
      * host subdomain
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder clearSubDomain() {
      subDomain = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'hostDesc' field.
      * host desc
      * @return The value.
      */
    public java.lang.String getHostDesc() {
      return hostDesc;
    }


    /**
      * Sets the value of the 'hostDesc' field.
      * host desc
      * @param value The value of 'hostDesc'.
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder setHostDesc(java.lang.String value) {
      validate(fields()[4], value);
      this.hostDesc = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'hostDesc' field has been set.
      * host desc
      * @return True if the 'hostDesc' field has been set, false otherwise.
      */
    public boolean hasHostDesc() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'hostDesc' field.
      * host desc
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder clearHostDesc() {
      hostDesc = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'hostOwner' field.
      * host owner
      * @return The value.
      */
    public java.lang.String getHostOwner() {
      return hostOwner;
    }


    /**
      * Sets the value of the 'hostOwner' field.
      * host owner
      * @param value The value of 'hostOwner'.
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder setHostOwner(java.lang.String value) {
      validate(fields()[5], value);
      this.hostOwner = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'hostOwner' field has been set.
      * host owner
      * @return True if the 'hostOwner' field has been set, false otherwise.
      */
    public boolean hasHostOwner() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'hostOwner' field.
      * host owner
      * @return This builder.
      */
    public net.lightapi.portal.host.HostUpdatedEvent.Builder clearHostOwner() {
      hostOwner = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HostUpdatedEvent build() {
      try {
        HostUpdatedEvent record = new HostUpdatedEvent();
        if (EventIdBuilder != null) {
          try {
            record.EventId = this.EventIdBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("EventId"));
            throw e;
          }
        } else {
          record.EventId = fieldSetFlags()[0] ? this.EventId : (com.networknt.kafka.common.EventId) defaultValue(fields()[0]);
        }
        record.hostId = fieldSetFlags()[1] ? this.hostId : (java.lang.String) defaultValue(fields()[1]);
        record.domain = fieldSetFlags()[2] ? this.domain : (java.lang.String) defaultValue(fields()[2]);
        record.subDomain = fieldSetFlags()[3] ? this.subDomain : (java.lang.String) defaultValue(fields()[3]);
        record.hostDesc = fieldSetFlags()[4] ? this.hostDesc : (java.lang.String) defaultValue(fields()[4]);
        record.hostOwner = fieldSetFlags()[5] ? this.hostOwner : (java.lang.String) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HostUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<HostUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HostUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<HostUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.EventId.customEncode(out);

    out.writeString(this.hostId);

    out.writeString(this.domain);

    out.writeString(this.subDomain);

    out.writeString(this.hostDesc);

    out.writeString(this.hostOwner);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.EventId == null) {
        this.EventId = new com.networknt.kafka.common.EventId();
      }
      this.EventId.customDecode(in);

      this.hostId = in.readString();

      this.domain = in.readString();

      this.subDomain = in.readString();

      this.hostDesc = in.readString();

      this.hostOwner = in.readString();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.EventId == null) {
            this.EventId = new com.networknt.kafka.common.EventId();
          }
          this.EventId.customDecode(in);
          break;

        case 1:
          this.hostId = in.readString();
          break;

        case 2:
          this.domain = in.readString();
          break;

        case 3:
          this.subDomain = in.readString();
          break;

        case 4:
          this.hostDesc = in.readString();
          break;

        case 5:
          this.hostOwner = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
