/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.lightapi.portal.instance;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InstanceUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -620280932815161063L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InstanceUpdatedEvent\",\"namespace\":\"net.lightapi.portal.instance\",\"fields\":[{\"name\":\"EventId\",\"type\":{\"type\":\"record\",\"name\":\"EventId\",\"namespace\":\"com.networknt.kafka.common\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"a unique identifier for the event\"},{\"name\":\"userId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the user who creates the event\"},{\"name\":\"hostId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the host which is the event is created\"},{\"name\":\"nonce\",\"type\":\"long\",\"doc\":\"the number of the transactions for the user\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"time the event is recorded\",\"default\":0},{\"name\":\"derived\",\"type\":\"boolean\",\"doc\":\"indicate if the event is derived from event processor\",\"default\":false}]}},{\"name\":\"instanceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"instance id\"},{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"product id\"},{\"name\":\"productVersion\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"product version\"},{\"name\":\"serviceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"service id\"},{\"name\":\"platformId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"platform id\"},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"value in json\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InstanceUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InstanceUpdatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InstanceUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InstanceUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InstanceUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InstanceUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InstanceUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InstanceUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InstanceUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.networknt.kafka.common.EventId EventId;
  /** instance id */
  private java.lang.String instanceId;
  /** product id */
  private java.lang.String productId;
  /** product version */
  private java.lang.String productVersion;
  /** service id */
  private java.lang.String serviceId;
  /** platform id */
  private java.lang.String platformId;
  /** value in json */
  private java.lang.String value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InstanceUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param EventId The new value for EventId
   * @param instanceId instance id
   * @param productId product id
   * @param productVersion product version
   * @param serviceId service id
   * @param platformId platform id
   * @param value value in json
   */
  public InstanceUpdatedEvent(com.networknt.kafka.common.EventId EventId, java.lang.String instanceId, java.lang.String productId, java.lang.String productVersion, java.lang.String serviceId, java.lang.String platformId, java.lang.String value) {
    this.EventId = EventId;
    this.instanceId = instanceId;
    this.productId = productId;
    this.productVersion = productVersion;
    this.serviceId = serviceId;
    this.platformId = platformId;
    this.value = value;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return EventId;
    case 1: return instanceId;
    case 2: return productId;
    case 3: return productVersion;
    case 4: return serviceId;
    case 5: return platformId;
    case 6: return value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: EventId = (com.networknt.kafka.common.EventId)value$; break;
    case 1: instanceId = value$ != null ? value$.toString() : null; break;
    case 2: productId = value$ != null ? value$.toString() : null; break;
    case 3: productVersion = value$ != null ? value$.toString() : null; break;
    case 4: serviceId = value$ != null ? value$.toString() : null; break;
    case 5: platformId = value$ != null ? value$.toString() : null; break;
    case 6: value = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'EventId' field.
   * @return The value of the 'EventId' field.
   */
  public com.networknt.kafka.common.EventId getEventId() {
    return EventId;
  }


  /**
   * Sets the value of the 'EventId' field.
   * @param value the value to set.
   */
  public void setEventId(com.networknt.kafka.common.EventId value) {
    this.EventId = value;
  }

  /**
   * Gets the value of the 'instanceId' field.
   * @return instance id
   */
  public java.lang.String getInstanceId() {
    return instanceId;
  }


  /**
   * Sets the value of the 'instanceId' field.
   * instance id
   * @param value the value to set.
   */
  public void setInstanceId(java.lang.String value) {
    this.instanceId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return product id
   */
  public java.lang.String getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * product id
   * @param value the value to set.
   */
  public void setProductId(java.lang.String value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'productVersion' field.
   * @return product version
   */
  public java.lang.String getProductVersion() {
    return productVersion;
  }


  /**
   * Sets the value of the 'productVersion' field.
   * product version
   * @param value the value to set.
   */
  public void setProductVersion(java.lang.String value) {
    this.productVersion = value;
  }

  /**
   * Gets the value of the 'serviceId' field.
   * @return service id
   */
  public java.lang.String getServiceId() {
    return serviceId;
  }


  /**
   * Sets the value of the 'serviceId' field.
   * service id
   * @param value the value to set.
   */
  public void setServiceId(java.lang.String value) {
    this.serviceId = value;
  }

  /**
   * Gets the value of the 'platformId' field.
   * @return platform id
   */
  public java.lang.String getPlatformId() {
    return platformId;
  }


  /**
   * Sets the value of the 'platformId' field.
   * platform id
   * @param value the value to set.
   */
  public void setPlatformId(java.lang.String value) {
    this.platformId = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return value in json
   */
  public java.lang.String getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * value in json
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Creates a new InstanceUpdatedEvent RecordBuilder.
   * @return A new InstanceUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.instance.InstanceUpdatedEvent.Builder newBuilder() {
    return new net.lightapi.portal.instance.InstanceUpdatedEvent.Builder();
  }

  /**
   * Creates a new InstanceUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InstanceUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.instance.InstanceUpdatedEvent.Builder newBuilder(net.lightapi.portal.instance.InstanceUpdatedEvent.Builder other) {
    if (other == null) {
      return new net.lightapi.portal.instance.InstanceUpdatedEvent.Builder();
    } else {
      return new net.lightapi.portal.instance.InstanceUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new InstanceUpdatedEvent RecordBuilder by copying an existing InstanceUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new InstanceUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.instance.InstanceUpdatedEvent.Builder newBuilder(net.lightapi.portal.instance.InstanceUpdatedEvent other) {
    if (other == null) {
      return new net.lightapi.portal.instance.InstanceUpdatedEvent.Builder();
    } else {
      return new net.lightapi.portal.instance.InstanceUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for InstanceUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InstanceUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<InstanceUpdatedEvent> {

    private com.networknt.kafka.common.EventId EventId;
    private com.networknt.kafka.common.EventId.Builder EventIdBuilder;
    /** instance id */
    private java.lang.String instanceId;
    /** product id */
    private java.lang.String productId;
    /** product version */
    private java.lang.String productVersion;
    /** service id */
    private java.lang.String serviceId;
    /** platform id */
    private java.lang.String platformId;
    /** value in json */
    private java.lang.String value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.lightapi.portal.instance.InstanceUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasEventIdBuilder()) {
        this.EventIdBuilder = com.networknt.kafka.common.EventId.newBuilder(other.getEventIdBuilder());
      }
      if (isValidValue(fields()[1], other.instanceId)) {
        this.instanceId = data().deepCopy(fields()[1].schema(), other.instanceId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productId)) {
        this.productId = data().deepCopy(fields()[2].schema(), other.productId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.productVersion)) {
        this.productVersion = data().deepCopy(fields()[3].schema(), other.productVersion);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.serviceId)) {
        this.serviceId = data().deepCopy(fields()[4].schema(), other.serviceId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.platformId)) {
        this.platformId = data().deepCopy(fields()[5].schema(), other.platformId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.value)) {
        this.value = data().deepCopy(fields()[6].schema(), other.value);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing InstanceUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(net.lightapi.portal.instance.InstanceUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = true;
      }
      this.EventIdBuilder = null;
      if (isValidValue(fields()[1], other.instanceId)) {
        this.instanceId = data().deepCopy(fields()[1].schema(), other.instanceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productId)) {
        this.productId = data().deepCopy(fields()[2].schema(), other.productId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productVersion)) {
        this.productVersion = data().deepCopy(fields()[3].schema(), other.productVersion);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.serviceId)) {
        this.serviceId = data().deepCopy(fields()[4].schema(), other.serviceId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.platformId)) {
        this.platformId = data().deepCopy(fields()[5].schema(), other.platformId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.value)) {
        this.value = data().deepCopy(fields()[6].schema(), other.value);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'EventId' field.
      * @return The value.
      */
    public com.networknt.kafka.common.EventId getEventId() {
      return EventId;
    }


    /**
      * Sets the value of the 'EventId' field.
      * @param value The value of 'EventId'.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setEventId(com.networknt.kafka.common.EventId value) {
      validate(fields()[0], value);
      this.EventIdBuilder = null;
      this.EventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'EventId' field has been set.
      * @return True if the 'EventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'EventId' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.networknt.kafka.common.EventId.Builder getEventIdBuilder() {
      if (EventIdBuilder == null) {
        if (hasEventId()) {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder(EventId));
        } else {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder());
        }
      }
      return EventIdBuilder;
    }

    /**
     * Sets the Builder instance for the 'EventId' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setEventIdBuilder(com.networknt.kafka.common.EventId.Builder value) {
      clearEventId();
      EventIdBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'EventId' field has an active Builder instance
     * @return True if the 'EventId' field has an active Builder instance
     */
    public boolean hasEventIdBuilder() {
      return EventIdBuilder != null;
    }

    /**
      * Clears the value of the 'EventId' field.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder clearEventId() {
      EventId = null;
      EventIdBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'instanceId' field.
      * instance id
      * @return The value.
      */
    public java.lang.String getInstanceId() {
      return instanceId;
    }


    /**
      * Sets the value of the 'instanceId' field.
      * instance id
      * @param value The value of 'instanceId'.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setInstanceId(java.lang.String value) {
      validate(fields()[1], value);
      this.instanceId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'instanceId' field has been set.
      * instance id
      * @return True if the 'instanceId' field has been set, false otherwise.
      */
    public boolean hasInstanceId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'instanceId' field.
      * instance id
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder clearInstanceId() {
      instanceId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * product id
      * @return The value.
      */
    public java.lang.String getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * product id
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setProductId(java.lang.String value) {
      validate(fields()[2], value);
      this.productId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * product id
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productId' field.
      * product id
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'productVersion' field.
      * product version
      * @return The value.
      */
    public java.lang.String getProductVersion() {
      return productVersion;
    }


    /**
      * Sets the value of the 'productVersion' field.
      * product version
      * @param value The value of 'productVersion'.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setProductVersion(java.lang.String value) {
      validate(fields()[3], value);
      this.productVersion = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'productVersion' field has been set.
      * product version
      * @return True if the 'productVersion' field has been set, false otherwise.
      */
    public boolean hasProductVersion() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'productVersion' field.
      * product version
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder clearProductVersion() {
      productVersion = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceId' field.
      * service id
      * @return The value.
      */
    public java.lang.String getServiceId() {
      return serviceId;
    }


    /**
      * Sets the value of the 'serviceId' field.
      * service id
      * @param value The value of 'serviceId'.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setServiceId(java.lang.String value) {
      validate(fields()[4], value);
      this.serviceId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceId' field has been set.
      * service id
      * @return True if the 'serviceId' field has been set, false otherwise.
      */
    public boolean hasServiceId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'serviceId' field.
      * service id
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder clearServiceId() {
      serviceId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'platformId' field.
      * platform id
      * @return The value.
      */
    public java.lang.String getPlatformId() {
      return platformId;
    }


    /**
      * Sets the value of the 'platformId' field.
      * platform id
      * @param value The value of 'platformId'.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setPlatformId(java.lang.String value) {
      validate(fields()[5], value);
      this.platformId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'platformId' field has been set.
      * platform id
      * @return True if the 'platformId' field has been set, false otherwise.
      */
    public boolean hasPlatformId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'platformId' field.
      * platform id
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder clearPlatformId() {
      platformId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * value in json
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * value in json
      * @param value The value of 'value'.
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder setValue(java.lang.String value) {
      validate(fields()[6], value);
      this.value = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * value in json
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'value' field.
      * value in json
      * @return This builder.
      */
    public net.lightapi.portal.instance.InstanceUpdatedEvent.Builder clearValue() {
      value = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InstanceUpdatedEvent build() {
      try {
        InstanceUpdatedEvent record = new InstanceUpdatedEvent();
        if (EventIdBuilder != null) {
          try {
            record.EventId = this.EventIdBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("EventId"));
            throw e;
          }
        } else {
          record.EventId = fieldSetFlags()[0] ? this.EventId : (com.networknt.kafka.common.EventId) defaultValue(fields()[0]);
        }
        record.instanceId = fieldSetFlags()[1] ? this.instanceId : (java.lang.String) defaultValue(fields()[1]);
        record.productId = fieldSetFlags()[2] ? this.productId : (java.lang.String) defaultValue(fields()[2]);
        record.productVersion = fieldSetFlags()[3] ? this.productVersion : (java.lang.String) defaultValue(fields()[3]);
        record.serviceId = fieldSetFlags()[4] ? this.serviceId : (java.lang.String) defaultValue(fields()[4]);
        record.platformId = fieldSetFlags()[5] ? this.platformId : (java.lang.String) defaultValue(fields()[5]);
        record.value = fieldSetFlags()[6] ? this.value : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InstanceUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<InstanceUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InstanceUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<InstanceUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.EventId.customEncode(out);

    out.writeString(this.instanceId);

    out.writeString(this.productId);

    out.writeString(this.productVersion);

    out.writeString(this.serviceId);

    out.writeString(this.platformId);

    out.writeString(this.value);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.EventId == null) {
        this.EventId = new com.networknt.kafka.common.EventId();
      }
      this.EventId.customDecode(in);

      this.instanceId = in.readString();

      this.productId = in.readString();

      this.productVersion = in.readString();

      this.serviceId = in.readString();

      this.platformId = in.readString();

      this.value = in.readString();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.EventId == null) {
            this.EventId = new com.networknt.kafka.common.EventId();
          }
          this.EventId.customDecode(in);
          break;

        case 1:
          this.instanceId = in.readString();
          break;

        case 2:
          this.productId = in.readString();
          break;

        case 3:
          this.productVersion = in.readString();
          break;

        case 4:
          this.serviceId = in.readString();
          break;

        case 5:
          this.platformId = in.readString();
          break;

        case 6:
          this.value = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}
