/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.lightapi.portal.user;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class HostUpdatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3464203276550706128L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HostUpdatedEvent\",\"namespace\":\"net.lightapi.portal.user\",\"fields\":[{\"name\":\"EventId\",\"type\":{\"type\":\"record\",\"name\":\"EventId\",\"namespace\":\"com.networknt.kafka.common\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"a unique identifier\"},{\"name\":\"nonce\",\"type\":\"long\",\"doc\":\"the number of the transactions for the user\"},{\"name\":\"derived\",\"type\":\"boolean\",\"doc\":\"indicate if the event is derived from event processor\",\"default\":false}]}},{\"name\":\"keyId\",\"type\":\"int\",\"doc\":\"keyId 0 host\"},{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host id is a UUID generated by the handler\"},{\"name\":\"desc\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"A short description of the organization\"},{\"name\":\"owner\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host owner id\"},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"host detail in JSON for other properties\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"time the event is recorded\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<HostUpdatedEvent> ENCODER =
      new BinaryMessageEncoder<HostUpdatedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<HostUpdatedEvent> DECODER =
      new BinaryMessageDecoder<HostUpdatedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<HostUpdatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<HostUpdatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<HostUpdatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<HostUpdatedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this HostUpdatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a HostUpdatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a HostUpdatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static HostUpdatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.networknt.kafka.common.EventId EventId;
  /** keyId 0 host */
  private int keyId;
  /** host id is a UUID generated by the handler */
  private java.lang.String id;
  /** A short description of the organization */
  private java.lang.String desc;
  /** host owner id */
  private java.lang.String owner;
  /** host detail in JSON for other properties */
  private java.lang.String value;
  /** time the event is recorded */
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HostUpdatedEvent() {}

  /**
   * All-args constructor.
   * @param EventId The new value for EventId
   * @param keyId keyId 0 host
   * @param id host id is a UUID generated by the handler
   * @param desc A short description of the organization
   * @param owner host owner id
   * @param value host detail in JSON for other properties
   * @param timestamp time the event is recorded
   */
  public HostUpdatedEvent(com.networknt.kafka.common.EventId EventId, java.lang.Integer keyId, java.lang.String id, java.lang.String desc, java.lang.String owner, java.lang.String value, java.lang.Long timestamp) {
    this.EventId = EventId;
    this.keyId = keyId;
    this.id = id;
    this.desc = desc;
    this.owner = owner;
    this.value = value;
    this.timestamp = timestamp;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return EventId;
    case 1: return keyId;
    case 2: return id;
    case 3: return desc;
    case 4: return owner;
    case 5: return value;
    case 6: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: EventId = (com.networknt.kafka.common.EventId)value$; break;
    case 1: keyId = (java.lang.Integer)value$; break;
    case 2: id = value$ != null ? value$.toString() : null; break;
    case 3: desc = value$ != null ? value$.toString() : null; break;
    case 4: owner = value$ != null ? value$.toString() : null; break;
    case 5: value = value$ != null ? value$.toString() : null; break;
    case 6: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'EventId' field.
   * @return The value of the 'EventId' field.
   */
  public com.networknt.kafka.common.EventId getEventId() {
    return EventId;
  }


  /**
   * Sets the value of the 'EventId' field.
   * @param value the value to set.
   */
  public void setEventId(com.networknt.kafka.common.EventId value) {
    this.EventId = value;
  }

  /**
   * Gets the value of the 'keyId' field.
   * @return keyId 0 host
   */
  public int getKeyId() {
    return keyId;
  }


  /**
   * Sets the value of the 'keyId' field.
   * keyId 0 host
   * @param value the value to set.
   */
  public void setKeyId(int value) {
    this.keyId = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return host id is a UUID generated by the handler
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * host id is a UUID generated by the handler
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'desc' field.
   * @return A short description of the organization
   */
  public java.lang.String getDesc() {
    return desc;
  }


  /**
   * Sets the value of the 'desc' field.
   * A short description of the organization
   * @param value the value to set.
   */
  public void setDesc(java.lang.String value) {
    this.desc = value;
  }

  /**
   * Gets the value of the 'owner' field.
   * @return host owner id
   */
  public java.lang.String getOwner() {
    return owner;
  }


  /**
   * Sets the value of the 'owner' field.
   * host owner id
   * @param value the value to set.
   */
  public void setOwner(java.lang.String value) {
    this.owner = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return host detail in JSON for other properties
   */
  public java.lang.String getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * host detail in JSON for other properties
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return time the event is recorded
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * time the event is recorded
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new HostUpdatedEvent RecordBuilder.
   * @return A new HostUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.user.HostUpdatedEvent.Builder newBuilder() {
    return new net.lightapi.portal.user.HostUpdatedEvent.Builder();
  }

  /**
   * Creates a new HostUpdatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new HostUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.user.HostUpdatedEvent.Builder newBuilder(net.lightapi.portal.user.HostUpdatedEvent.Builder other) {
    if (other == null) {
      return new net.lightapi.portal.user.HostUpdatedEvent.Builder();
    } else {
      return new net.lightapi.portal.user.HostUpdatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new HostUpdatedEvent RecordBuilder by copying an existing HostUpdatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new HostUpdatedEvent RecordBuilder
   */
  public static net.lightapi.portal.user.HostUpdatedEvent.Builder newBuilder(net.lightapi.portal.user.HostUpdatedEvent other) {
    if (other == null) {
      return new net.lightapi.portal.user.HostUpdatedEvent.Builder();
    } else {
      return new net.lightapi.portal.user.HostUpdatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for HostUpdatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HostUpdatedEvent>
    implements org.apache.avro.data.RecordBuilder<HostUpdatedEvent> {

    private com.networknt.kafka.common.EventId EventId;
    private com.networknt.kafka.common.EventId.Builder EventIdBuilder;
    /** keyId 0 host */
    private int keyId;
    /** host id is a UUID generated by the handler */
    private java.lang.String id;
    /** A short description of the organization */
    private java.lang.String desc;
    /** host owner id */
    private java.lang.String owner;
    /** host detail in JSON for other properties */
    private java.lang.String value;
    /** time the event is recorded */
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.lightapi.portal.user.HostUpdatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasEventIdBuilder()) {
        this.EventIdBuilder = com.networknt.kafka.common.EventId.newBuilder(other.getEventIdBuilder());
      }
      if (isValidValue(fields()[1], other.keyId)) {
        this.keyId = data().deepCopy(fields()[1].schema(), other.keyId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.id)) {
        this.id = data().deepCopy(fields()[2].schema(), other.id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.desc)) {
        this.desc = data().deepCopy(fields()[3].schema(), other.desc);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.owner)) {
        this.owner = data().deepCopy(fields()[4].schema(), other.owner);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.value)) {
        this.value = data().deepCopy(fields()[5].schema(), other.value);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing HostUpdatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(net.lightapi.portal.user.HostUpdatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = true;
      }
      this.EventIdBuilder = null;
      if (isValidValue(fields()[1], other.keyId)) {
        this.keyId = data().deepCopy(fields()[1].schema(), other.keyId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.id)) {
        this.id = data().deepCopy(fields()[2].schema(), other.id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.desc)) {
        this.desc = data().deepCopy(fields()[3].schema(), other.desc);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.owner)) {
        this.owner = data().deepCopy(fields()[4].schema(), other.owner);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.value)) {
        this.value = data().deepCopy(fields()[5].schema(), other.value);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'EventId' field.
      * @return The value.
      */
    public com.networknt.kafka.common.EventId getEventId() {
      return EventId;
    }


    /**
      * Sets the value of the 'EventId' field.
      * @param value The value of 'EventId'.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder setEventId(com.networknt.kafka.common.EventId value) {
      validate(fields()[0], value);
      this.EventIdBuilder = null;
      this.EventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'EventId' field has been set.
      * @return True if the 'EventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'EventId' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.networknt.kafka.common.EventId.Builder getEventIdBuilder() {
      if (EventIdBuilder == null) {
        if (hasEventId()) {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder(EventId));
        } else {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder());
        }
      }
      return EventIdBuilder;
    }

    /**
     * Sets the Builder instance for the 'EventId' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public net.lightapi.portal.user.HostUpdatedEvent.Builder setEventIdBuilder(com.networknt.kafka.common.EventId.Builder value) {
      clearEventId();
      EventIdBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'EventId' field has an active Builder instance
     * @return True if the 'EventId' field has an active Builder instance
     */
    public boolean hasEventIdBuilder() {
      return EventIdBuilder != null;
    }

    /**
      * Clears the value of the 'EventId' field.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder clearEventId() {
      EventId = null;
      EventIdBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'keyId' field.
      * keyId 0 host
      * @return The value.
      */
    public int getKeyId() {
      return keyId;
    }


    /**
      * Sets the value of the 'keyId' field.
      * keyId 0 host
      * @param value The value of 'keyId'.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder setKeyId(int value) {
      validate(fields()[1], value);
      this.keyId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'keyId' field has been set.
      * keyId 0 host
      * @return True if the 'keyId' field has been set, false otherwise.
      */
    public boolean hasKeyId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'keyId' field.
      * keyId 0 host
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder clearKeyId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * host id is a UUID generated by the handler
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * host id is a UUID generated by the handler
      * @param value The value of 'id'.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder setId(java.lang.String value) {
      validate(fields()[2], value);
      this.id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * host id is a UUID generated by the handler
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'id' field.
      * host id is a UUID generated by the handler
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder clearId() {
      id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'desc' field.
      * A short description of the organization
      * @return The value.
      */
    public java.lang.String getDesc() {
      return desc;
    }


    /**
      * Sets the value of the 'desc' field.
      * A short description of the organization
      * @param value The value of 'desc'.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder setDesc(java.lang.String value) {
      validate(fields()[3], value);
      this.desc = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'desc' field has been set.
      * A short description of the organization
      * @return True if the 'desc' field has been set, false otherwise.
      */
    public boolean hasDesc() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'desc' field.
      * A short description of the organization
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder clearDesc() {
      desc = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'owner' field.
      * host owner id
      * @return The value.
      */
    public java.lang.String getOwner() {
      return owner;
    }


    /**
      * Sets the value of the 'owner' field.
      * host owner id
      * @param value The value of 'owner'.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder setOwner(java.lang.String value) {
      validate(fields()[4], value);
      this.owner = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'owner' field has been set.
      * host owner id
      * @return True if the 'owner' field has been set, false otherwise.
      */
    public boolean hasOwner() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'owner' field.
      * host owner id
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder clearOwner() {
      owner = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * host detail in JSON for other properties
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * host detail in JSON for other properties
      * @param value The value of 'value'.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder setValue(java.lang.String value) {
      validate(fields()[5], value);
      this.value = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * host detail in JSON for other properties
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'value' field.
      * host detail in JSON for other properties
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder clearValue() {
      value = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * time the event is recorded
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * time the event is recorded
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder setTimestamp(long value) {
      validate(fields()[6], value);
      this.timestamp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * time the event is recorded
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * time the event is recorded
      * @return This builder.
      */
    public net.lightapi.portal.user.HostUpdatedEvent.Builder clearTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public HostUpdatedEvent build() {
      try {
        HostUpdatedEvent record = new HostUpdatedEvent();
        if (EventIdBuilder != null) {
          try {
            record.EventId = this.EventIdBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("EventId"));
            throw e;
          }
        } else {
          record.EventId = fieldSetFlags()[0] ? this.EventId : (com.networknt.kafka.common.EventId) defaultValue(fields()[0]);
        }
        record.keyId = fieldSetFlags()[1] ? this.keyId : (java.lang.Integer) defaultValue(fields()[1]);
        record.id = fieldSetFlags()[2] ? this.id : (java.lang.String) defaultValue(fields()[2]);
        record.desc = fieldSetFlags()[3] ? this.desc : (java.lang.String) defaultValue(fields()[3]);
        record.owner = fieldSetFlags()[4] ? this.owner : (java.lang.String) defaultValue(fields()[4]);
        record.value = fieldSetFlags()[5] ? this.value : (java.lang.String) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<HostUpdatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<HostUpdatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<HostUpdatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<HostUpdatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.EventId.customEncode(out);

    out.writeInt(this.keyId);

    out.writeString(this.id);

    out.writeString(this.desc);

    out.writeString(this.owner);

    out.writeString(this.value);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.EventId == null) {
        this.EventId = new com.networknt.kafka.common.EventId();
      }
      this.EventId.customDecode(in);

      this.keyId = in.readInt();

      this.id = in.readString();

      this.desc = in.readString();

      this.owner = in.readString();

      this.value = in.readString();

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.EventId == null) {
            this.EventId = new com.networknt.kafka.common.EventId();
          }
          this.EventId.customDecode(in);
          break;

        case 1:
          this.keyId = in.readInt();
          break;

        case 2:
          this.id = in.readString();
          break;

        case 3:
          this.desc = in.readString();
          break;

        case 4:
          this.owner = in.readString();
          break;

        case 5:
          this.value = in.readString();
          break;

        case 6:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










