/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.lightapi.portal.covid;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CityMapCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9148672086573096837L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CityMapCreatedEvent\",\"namespace\":\"net.lightapi.portal.covid\",\"fields\":[{\"name\":\"EventId\",\"type\":{\"type\":\"record\",\"name\":\"EventId\",\"namespace\":\"com.networknt.kafka.common\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"a unique identifier\"},{\"name\":\"nonce\",\"type\":\"long\",\"doc\":\"the number of the transactions for the user\"},{\"name\":\"derived\",\"type\":\"boolean\",\"doc\":\"indicate if the event is derived from event processor\",\"default\":false}]}},{\"name\":\"country\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"country\"},{\"name\":\"province\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"province\"},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"city\"},{\"name\":\"latitude\",\"type\":\"double\",\"doc\":\"city latitude\"},{\"name\":\"longitude\",\"type\":\"double\",\"doc\":\"city longitude\"},{\"name\":\"zoom\",\"type\":\"int\",\"doc\":\"initial zoom\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"time the event is recorded\",\"default\":0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CityMapCreatedEvent> ENCODER =
      new BinaryMessageEncoder<CityMapCreatedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CityMapCreatedEvent> DECODER =
      new BinaryMessageDecoder<CityMapCreatedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CityMapCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CityMapCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CityMapCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CityMapCreatedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CityMapCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CityMapCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CityMapCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CityMapCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private com.networknt.kafka.common.EventId EventId;
  /** country */
   private java.lang.String country;
  /** province */
   private java.lang.String province;
  /** city */
   private java.lang.String city;
  /** city latitude */
   private double latitude;
  /** city longitude */
   private double longitude;
  /** initial zoom */
   private int zoom;
  /** time the event is recorded */
   private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CityMapCreatedEvent() {}

  /**
   * All-args constructor.
   * @param EventId The new value for EventId
   * @param country country
   * @param province province
   * @param city city
   * @param latitude city latitude
   * @param longitude city longitude
   * @param zoom initial zoom
   * @param timestamp time the event is recorded
   */
  public CityMapCreatedEvent(com.networknt.kafka.common.EventId EventId, java.lang.String country, java.lang.String province, java.lang.String city, java.lang.Double latitude, java.lang.Double longitude, java.lang.Integer zoom, java.lang.Long timestamp) {
    this.EventId = EventId;
    this.country = country;
    this.province = province;
    this.city = city;
    this.latitude = latitude;
    this.longitude = longitude;
    this.zoom = zoom;
    this.timestamp = timestamp;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return EventId;
    case 1: return country;
    case 2: return province;
    case 3: return city;
    case 4: return latitude;
    case 5: return longitude;
    case 6: return zoom;
    case 7: return timestamp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: EventId = (com.networknt.kafka.common.EventId)value$; break;
    case 1: country = value$ != null ? value$.toString() : null; break;
    case 2: province = value$ != null ? value$.toString() : null; break;
    case 3: city = value$ != null ? value$.toString() : null; break;
    case 4: latitude = (java.lang.Double)value$; break;
    case 5: longitude = (java.lang.Double)value$; break;
    case 6: zoom = (java.lang.Integer)value$; break;
    case 7: timestamp = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'EventId' field.
   * @return The value of the 'EventId' field.
   */
  public com.networknt.kafka.common.EventId getEventId() {
    return EventId;
  }


  /**
   * Sets the value of the 'EventId' field.
   * @param value the value to set.
   */
  public void setEventId(com.networknt.kafka.common.EventId value) {
    this.EventId = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return country
   */
  public java.lang.String getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * country
   * @param value the value to set.
   */
  public void setCountry(java.lang.String value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'province' field.
   * @return province
   */
  public java.lang.String getProvince() {
    return province;
  }


  /**
   * Sets the value of the 'province' field.
   * province
   * @param value the value to set.
   */
  public void setProvince(java.lang.String value) {
    this.province = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return city
   */
  public java.lang.String getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * city
   * @param value the value to set.
   */
  public void setCity(java.lang.String value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return city latitude
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * city latitude
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return city longitude
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * city longitude
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'zoom' field.
   * @return initial zoom
   */
  public int getZoom() {
    return zoom;
  }


  /**
   * Sets the value of the 'zoom' field.
   * initial zoom
   * @param value the value to set.
   */
  public void setZoom(int value) {
    this.zoom = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return time the event is recorded
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * time the event is recorded
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new CityMapCreatedEvent RecordBuilder.
   * @return A new CityMapCreatedEvent RecordBuilder
   */
  public static net.lightapi.portal.covid.CityMapCreatedEvent.Builder newBuilder() {
    return new net.lightapi.portal.covid.CityMapCreatedEvent.Builder();
  }

  /**
   * Creates a new CityMapCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CityMapCreatedEvent RecordBuilder
   */
  public static net.lightapi.portal.covid.CityMapCreatedEvent.Builder newBuilder(net.lightapi.portal.covid.CityMapCreatedEvent.Builder other) {
    if (other == null) {
      return new net.lightapi.portal.covid.CityMapCreatedEvent.Builder();
    } else {
      return new net.lightapi.portal.covid.CityMapCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new CityMapCreatedEvent RecordBuilder by copying an existing CityMapCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new CityMapCreatedEvent RecordBuilder
   */
  public static net.lightapi.portal.covid.CityMapCreatedEvent.Builder newBuilder(net.lightapi.portal.covid.CityMapCreatedEvent other) {
    if (other == null) {
      return new net.lightapi.portal.covid.CityMapCreatedEvent.Builder();
    } else {
      return new net.lightapi.portal.covid.CityMapCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CityMapCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CityMapCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<CityMapCreatedEvent> {

    private com.networknt.kafka.common.EventId EventId;
    private com.networknt.kafka.common.EventId.Builder EventIdBuilder;
    /** country */
    private java.lang.String country;
    /** province */
    private java.lang.String province;
    /** city */
    private java.lang.String city;
    /** city latitude */
    private double latitude;
    /** city longitude */
    private double longitude;
    /** initial zoom */
    private int zoom;
    /** time the event is recorded */
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.lightapi.portal.covid.CityMapCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasEventIdBuilder()) {
        this.EventIdBuilder = com.networknt.kafka.common.EventId.newBuilder(other.getEventIdBuilder());
      }
      if (isValidValue(fields()[1], other.country)) {
        this.country = data().deepCopy(fields()[1].schema(), other.country);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.province)) {
        this.province = data().deepCopy(fields()[2].schema(), other.province);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.city)) {
        this.city = data().deepCopy(fields()[3].schema(), other.city);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.zoom)) {
        this.zoom = data().deepCopy(fields()[6].schema(), other.zoom);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing CityMapCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(net.lightapi.portal.covid.CityMapCreatedEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.EventId)) {
        this.EventId = data().deepCopy(fields()[0].schema(), other.EventId);
        fieldSetFlags()[0] = true;
      }
      this.EventIdBuilder = null;
      if (isValidValue(fields()[1], other.country)) {
        this.country = data().deepCopy(fields()[1].schema(), other.country);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.province)) {
        this.province = data().deepCopy(fields()[2].schema(), other.province);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.city)) {
        this.city = data().deepCopy(fields()[3].schema(), other.city);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.latitude)) {
        this.latitude = data().deepCopy(fields()[4].schema(), other.latitude);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.longitude)) {
        this.longitude = data().deepCopy(fields()[5].schema(), other.longitude);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.zoom)) {
        this.zoom = data().deepCopy(fields()[6].schema(), other.zoom);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'EventId' field.
      * @return The value.
      */
    public com.networknt.kafka.common.EventId getEventId() {
      return EventId;
    }


    /**
      * Sets the value of the 'EventId' field.
      * @param value The value of 'EventId'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setEventId(com.networknt.kafka.common.EventId value) {
      validate(fields()[0], value);
      this.EventIdBuilder = null;
      this.EventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'EventId' field has been set.
      * @return True if the 'EventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'EventId' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.networknt.kafka.common.EventId.Builder getEventIdBuilder() {
      if (EventIdBuilder == null) {
        if (hasEventId()) {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder(EventId));
        } else {
          setEventIdBuilder(com.networknt.kafka.common.EventId.newBuilder());
        }
      }
      return EventIdBuilder;
    }

    /**
     * Sets the Builder instance for the 'EventId' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setEventIdBuilder(com.networknt.kafka.common.EventId.Builder value) {
      clearEventId();
      EventIdBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'EventId' field has an active Builder instance
     * @return True if the 'EventId' field has an active Builder instance
     */
    public boolean hasEventIdBuilder() {
      return EventIdBuilder != null;
    }

    /**
      * Clears the value of the 'EventId' field.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearEventId() {
      EventId = null;
      EventIdBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * country
      * @return The value.
      */
    public java.lang.String getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * country
      * @param value The value of 'country'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setCountry(java.lang.String value) {
      validate(fields()[1], value);
      this.country = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * country
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'country' field.
      * country
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearCountry() {
      country = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'province' field.
      * province
      * @return The value.
      */
    public java.lang.String getProvince() {
      return province;
    }


    /**
      * Sets the value of the 'province' field.
      * province
      * @param value The value of 'province'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setProvince(java.lang.String value) {
      validate(fields()[2], value);
      this.province = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'province' field has been set.
      * province
      * @return True if the 'province' field has been set, false otherwise.
      */
    public boolean hasProvince() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'province' field.
      * province
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearProvince() {
      province = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * city
      * @return The value.
      */
    public java.lang.String getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * city
      * @param value The value of 'city'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setCity(java.lang.String value) {
      validate(fields()[3], value);
      this.city = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * city
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'city' field.
      * city
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearCity() {
      city = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * city latitude
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * city latitude
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setLatitude(double value) {
      validate(fields()[4], value);
      this.latitude = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * city latitude
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'latitude' field.
      * city latitude
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearLatitude() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * city longitude
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * city longitude
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setLongitude(double value) {
      validate(fields()[5], value);
      this.longitude = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * city longitude
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'longitude' field.
      * city longitude
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearLongitude() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'zoom' field.
      * initial zoom
      * @return The value.
      */
    public int getZoom() {
      return zoom;
    }


    /**
      * Sets the value of the 'zoom' field.
      * initial zoom
      * @param value The value of 'zoom'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setZoom(int value) {
      validate(fields()[6], value);
      this.zoom = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'zoom' field has been set.
      * initial zoom
      * @return True if the 'zoom' field has been set, false otherwise.
      */
    public boolean hasZoom() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'zoom' field.
      * initial zoom
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearZoom() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * time the event is recorded
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * time the event is recorded
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder setTimestamp(long value) {
      validate(fields()[7], value);
      this.timestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * time the event is recorded
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * time the event is recorded
      * @return This builder.
      */
    public net.lightapi.portal.covid.CityMapCreatedEvent.Builder clearTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CityMapCreatedEvent build() {
      try {
        CityMapCreatedEvent record = new CityMapCreatedEvent();
        if (EventIdBuilder != null) {
          try {
            record.EventId = this.EventIdBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("EventId"));
            throw e;
          }
        } else {
          record.EventId = fieldSetFlags()[0] ? this.EventId : (com.networknt.kafka.common.EventId) defaultValue(fields()[0]);
        }
        record.country = fieldSetFlags()[1] ? this.country : (java.lang.String) defaultValue(fields()[1]);
        record.province = fieldSetFlags()[2] ? this.province : (java.lang.String) defaultValue(fields()[2]);
        record.city = fieldSetFlags()[3] ? this.city : (java.lang.String) defaultValue(fields()[3]);
        record.latitude = fieldSetFlags()[4] ? this.latitude : (java.lang.Double) defaultValue(fields()[4]);
        record.longitude = fieldSetFlags()[5] ? this.longitude : (java.lang.Double) defaultValue(fields()[5]);
        record.zoom = fieldSetFlags()[6] ? this.zoom : (java.lang.Integer) defaultValue(fields()[6]);
        record.timestamp = fieldSetFlags()[7] ? this.timestamp : (java.lang.Long) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CityMapCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CityMapCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CityMapCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<CityMapCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.EventId.customEncode(out);

    out.writeString(this.country);

    out.writeString(this.province);

    out.writeString(this.city);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

    out.writeInt(this.zoom);

    out.writeLong(this.timestamp);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.EventId == null) {
        this.EventId = new com.networknt.kafka.common.EventId();
      }
      this.EventId.customDecode(in);

      this.country = in.readString();

      this.province = in.readString();

      this.city = in.readString();

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

      this.zoom = in.readInt();

      this.timestamp = in.readLong();

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.EventId == null) {
            this.EventId = new com.networknt.kafka.common.EventId();
          }
          this.EventId.customDecode(in);
          break;

        case 1:
          this.country = in.readString();
          break;

        case 2:
          this.province = in.readString();
          break;

        case 3:
          this.city = in.readString();
          break;

        case 4:
          this.latitude = in.readDouble();
          break;

        case 5:
          this.longitude = in.readDouble();
          break;

        case 6:
          this.zoom = in.readInt();
          break;

        case 7:
          this.timestamp = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










