# This is a configuration file for light-portal service
# Indicate if we need to send out the confirmation email during user registration
sendEmail: ${portal.sendEmail:false}
# The event topic for user-command
topic: ${portal.topic:portal-event}
# Indicate if the portal is running in multi-tenent mode. Default is false.
multitenancy: ${portal.multitenancy:false}
# The host of the server that accepts the email confirmation
cmdHost: ${portal.cmdHost:https://localhost:8439}
# The command path of the server that accepts the email confirmation
cmdPath: ${portal.cmdPath:/portal/command?cmd=}
# The host for password reset. This is usually the login view site.
resetHost: ${portal.resetHost:https://localhost:3000}
# The host for the portal. This is usually the portal view site.
portalHost: ${portal.portalHost:https://localhost:3000}
# Admin user email for the bootstrap
admin: ${portal.admin:steve.hu@lightapi.net}
# Portal data folder for contents that are not suitable for Kafka
dataPath: ${portal.dataPath:/data}

# Schedule Streams
# Kafka Streams Schedule application.id which is the consumer group.id
scheduleApplicationId: ${portal.scheduleApplication:schedule}
